name = "api"
main = "src/worker.ts"
compatibility_date = "2023-11-21"
send_metrics = false
node_compat = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "DNP"
database_id = "1b2a71bc-577b-4ae3-a9a5-747488198641"

[triggers]
# At 9 AM every day
crons = [ "0 9 * * *" ]
