name: 'Deploy to Cloudflare Workers'

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Migrate database
        run: npm run migrate
        env:
          NO_D1_WARNING: true
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.3.2
        with:
          wranglerVersion: '3.15.0'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy src/worker.ts
          packageManager: npm
          secrets: |
            MOLLIE_API_KEY
            CI
        env:
          MOLLIE_API_KEY: ${{ secrets.MOLLIE_API_KEY }}
          CI: true
          NO_D1_WARNING: true
